### ISSUE TITLE
Requesting rockspec change for lua-resty-session

### ISSUE THREAD

**Issue by csmcgee** [Kong/kong-plugin-session#15]
Currently `lua-resty-session` is locked to version 2.24 ([ref](https://github.com/Kong/kong-plugin-session/blob/master/kong-plugin-session-2.2.0-1.rockspec#L20)).

Since this plugin is bundled with kong, the `lua-resty-session` plugin is installed by default with its docker image.

Chrome recently pushed out an update regarding cookies and the usage of samesite. `lua-resty-session` has made an [update](https://github.com/bungle/lua-resty-session/pull/83) to support this change and is supported in version 2.26.

Thus, in order to support this change by Chrome - we have to `luarocks install --force` to ensure the most up to date package is used. (at least to my knowledge).

Can we make this dependency less strict (i.e `lua-resty-session >= 2.24`)? Or just bump the version?

Thank you.

**Comment by hishamhm** [comment]
@csmcgee a new release of lua-resty-session is coming soon, so we will bump this when that is released (and before the next Kong release). Thank you for the report!

**Comment by csmcgee** [comment]
Thank you for your response. I am closing the issue.
