### ISSUE TITLE
kong-plugin-session-1.0.0-1.rockspec removed 

### ISSUE THREAD

**Issue by Jojoooo1** [Kong/kong-plugin-session#7]
It seems that kong-plugin-session-1.0.0-1.rockspec file is not available anymore, any special reason for deleting it ?

**Comment by darrenjennings** [comment]
@Jojoooo1 you are correct, thanks for catching this. We host on luarocks, so the registry has it there https://luarocks.org/manifests/kong/kong-plugin-session-1.0.1-1.rockspec but it did not get pushed to `master`. Should be there now thanks!

**Comment by darrenjennings** [comment]
I have also re-released the latest tag so that luarocks `tag` will point to a repo with the rockspec included.
